### ISSUE TITLE
Name clash

### ISSUE THREAD

**Issue by titanix** [WinteryFox/JibikiAPI#32]
Hello WinteryFox,

I see you started a Japanese-English dictionary named Jibiki that's still in beta, which looks nice. I would like to inform you that there is already an open-source project in the same space (Japanese dictionary) with the same name, in which I'm a contributor.

[jibiki.fr](https://jibiki.fr/) is the instance dedicated to the improvement of a Japanese-French dictionary.

[jibiki (software)](https://github.com/mangeot/jibiki) is the underlying lexical editing platform, created by @mangeot

So, you might wanted to reconsider the public naming of your project when going out of beta, as it's already used for an open-source project mentioned in multiples scientific publications.

Regards,
LL

**Comment by WinteryFox** [comment]
Hi there,

Thanks for making me aware of the other projects with the same name, however I do not think I will be changing the name (I also don't even have the money to buy a different domain, so even if I wanted to, I can't). Maybe if someone comes up with a great name I will consider it but for now, it will remain Jibiki.app.

Sincerely,
Amy.
