### ISSUE TITLE
Allowing CORS on APIs

### ISSUE THREAD

**Issue by jamesrwaugh** [WinteryFox/JibikiAPI#33]
Hey there,

I'm building a webapp that uses Jibiki for retrieving Japanese sentences--I previously made a command line tool (https://github.com/jamesrwaugh/kyoro/blob/master/acquisition/jikibisentenceretriever.go#L39)  that used the API, but I see CORS is not enabled so my new app can't complete the request.

I noticed only support for credentials is enabled here:
https://github.com/WinteryFox/JibikiAPI/blob/master/src/main/kotlin/app/jibiki/controller/ApiController.kt#L10

Have you considered allowing all origins here, or another way to access the API from a web app?

Thanks again

**Comment by WinteryFox** [comment]
Sure I'll open up CORS, I'll close this for you when I get to it (possibly later today)

**Comment by jamesrwaugh** [comment]
@WinteryFox Did you get a chance to look at this one?

**Comment by WinteryFox** [comment]
After thinking about this a bit more, I've decided that I unfortunately cannot open up CORS. The proper way for you to handle this would be to make some kind of backend that your client makes a request to, that way your backend would be the one to hit the API and thus CORS would not be an issue at all. Unfortunately I cannot remove CORS for security reasons.

**Comment by jamesrwaugh** [comment]
That was my workaround in the meantime, I'll go ahead with that then.
Thank you!

**Comment by WinteryFox** [comment]
I'd like to see the thing you're making sometime if you want to show me too! I'm very happy that people are actually using the API haha.

**Comment by jamesrwaugh** [comment]
> I'd like to see the thing you're making sometime if you want to show me too! I'm very happy that people are actually using the API haha.

Sure. You can find the source here, purely WIP at the moment https://github.com/KyoroTeam/kyoro-ui

I'm developing an Anki addon for Japanese sentence card mining based off a previous one I linked in the opening comment. It involves pulling data from multiple sources for sentences, and AFAIK there really is nothing else for an API for translated sentences (besides maybe JMDict), and especially Tatoeba-based data. Previously Jisho required me to scrape their site before I saw your original Reddit post announcing the project. Honestly I'm not sure why this API isn't more popular, as [Tatoeba doesn't have an API](https://en.wiki.tatoeba.org/articles/show/faq).

You can see the workaround of using a local service for it here
https://github.com/KyoroTeam/kyoro-ui/blob/master/app/src/components/SearchBar.svelte#L15

If you'd like to know anything I'm Pwnsian#1610 on Discord.
