### ISSUE TITLE
Document URL escape requirement of Japanese strings in API

### ISSUE THREAD

**Issue by jamesrwaugh** [WinteryFox/JibikiAPI#8]
Hi,

Nice work so far, thanks! Trying out the API, I found I received nothing but a 400 Bad Request when trying to use the sentence API with Japanese text as a query, while English text worked fine. I found I needed to URL escape the text, and it works well.

I suppose this is expected as Jisho for example has the same behavior, but it might help if the docs made a note of it.

`curl https://api.jibiki.app/sentences?query=やすい`
400 Bad Request

`curl https://api.jibiki.app/sentences?query=%E3%82%84%E3%81%99%E3%81%84`
200 OK

**Comment by vendethiel** [comment]
You probably want to use `curl --data-urlencode=...`. Need to check if you're supposed to pass non-urlencoded params, as per the spec.

**Comment by jamesrwaugh** [comment]
Yes, I think this is just a matter of needing to URL escape the query. I'll go ahead and close this, if there is any other issue, please reopen @WinteryFox
